#!/usr/bin/env bash

set -o pipefail

tmpdir=$(mktemp -d)
trap 'rm -r $tmpdir' SIGINT EXIT

function choose() {
    fzf --delimiter '\t' \
        --height 40% \
        --header "Enter: Primary Action, Alt-enter: list actions, Alt+r: Reload List, Alt+space: Show Preview, Escape: Go Back" \
        --expect "enter,alt-enter" \
        --with-nth 1,2 \
        --nth 1,2 \
        --preview "echo {3} | jq -c .preview | lazy run 2> /dev/null || echo No Preview" \
        --preview-window "hidden:wrap" \
        --reverse \
        --cycle \
        --bind "alt-r:reload(cat $tmpdir/current | lazy ref --skip-cache | jq -r '\"\(.title)\t\(.subtitle)\t\(.actions[0])\t\(.)\"')" \
        --bind "alt-space:toggle-preview"
}

function step() {
    rows="$(jq -r '. | "\(.title)\t\(.subtitle)\t\(.)"' <"$1")"
    selectedItem="$(choose <<<"$rows")"
    exitCode="$?"
    if [ "$exitCode" -eq 2 ]; then
        exit 1
    elif [ "$exitCode" -eq 130 ]; then
        return 1
    fi

    row=$(tail -n 1 <<<"$selectedItem")
    item=$(awk -F '\t' '{ print $3 }' <<<"$row")
    shortcut=$(head -n 1 <<<"$selectedItem")
    if [ "$shortcut" = "enter" ]; then
        jq -c .actions[0] <<<"$item"
    elif [ "$shortcut" = "alt-enter" ]; then
        action=$(jq -rc '.actions[] | "\(.title)\t\(.)"' <<<"$item" \
            | fzf --delimiter '\t' --with-nth 1 --nth 1 --height 40% --reverse --cycle)

        if [ "$?" -eq 130 ]; then
            step "$1"
            return "$?"
        fi

        awk -F '\t' '{ print $2 }' <<<"$action"
    fi
}

# Handle navigation between lists
function navigate() {
    if ! step "$tmpdir/$step_index"; then
        if [ "$step_index" -eq 0 ]; then
            exit 0
        fi
        step_index=$((step_index - 1))
        navigate "$step_index"
    fi
}

items="$(lazy ls)"
step_index=0
while true; do
    printf "%s" "$items" >"$tmpdir/$step_index"
    navigate >"$tmpdir/next"

    action_type="$(jq -r .type <"$tmpdir/next")"
    if [ "$action_type" = "push" ]; then
        set -e
        items="$(lazy ls - <"$tmpdir/next")"
        set +e

        step_index=$((step_index + 1))
        cp "$tmpdir/next" "$tmpdir/current"
    else
        lazy run <"$tmpdir/next"
        exit 0
    fi
done
